steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/callme-backend/fastapi-backend:$SHORT_SHA', './backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/callme-backend/fastapi-backend:$SHORT_SHA']

  - name: 'gcr.io/google-cloud-sdk/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-backend'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/callme-backend/fastapi-backend:$SHORT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/callme-backend/fastapi-backend:$SHORT_SHA'